// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	user "AltaStore/business/user"

	mock "github.com/stretchr/testify/mock"

	userauth "AltaStore/business/userauth"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateToken provides a mock function with given fields: _a0
func (_m *Service) CreateToken(_a0 *user.User) (*userauth.TokenDetails, error) {
	ret := _m.Called(_a0)

	var r0 *userauth.TokenDetails
	if rf, ok := ret.Get(0).(func(*user.User) *userauth.TokenDetails); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userauth.TokenDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*user.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserLogin provides a mock function with given fields: email, password
func (_m *Service) UserLogin(email string, password string) (string, error) {
	ret := _m.Called(email, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
