// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	product "AltaStore/business/product"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// DeleteProduct provides a mock function with given fields: Product
func (_m *Repository) DeleteProduct(Product product.Product) error {
	ret := _m.Called(Product)

	var r0 error
	if rf, ok := ret.Get(0).(func(product.Product) error); ok {
		r0 = rf(Product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindProductByCode provides a mock function with given fields: code
func (_m *Repository) FindProductByCode(code string) (*product.Product, error) {
	ret := _m.Called(code)

	var r0 *product.Product
	if rf, ok := ret.Get(0).(func(string) *product.Product); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindProductById provides a mock function with given fields: id
func (_m *Repository) FindProductById(id string) (*product.Product, error) {
	ret := _m.Called(id)

	var r0 *product.Product
	if rf, ok := ret.Get(0).(func(string) *product.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllProduct provides a mock function with given fields:
func (_m *Repository) GetAllProduct() (*[]product.Product, error) {
	ret := _m.Called()

	var r0 *[]product.Product
	if rf, ok := ret.Get(0).(func() *[]product.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]product.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllProductByParameter provides a mock function with given fields: id, isActive, categoryName, code, name
func (_m *Repository) GetAllProductByParameter(id string, isActive string, categoryName string, code string, name string) (*[]product.Product, error) {
	ret := _m.Called(id, isActive, categoryName, code, name)

	var r0 *[]product.Product
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) *[]product.Product); ok {
		r0 = rf(id, isActive, categoryName, code, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]product.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(id, isActive, categoryName, code, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertProduct provides a mock function with given fields: Product
func (_m *Repository) InsertProduct(Product product.Product) error {
	ret := _m.Called(Product)

	var r0 error
	if rf, ok := ret.Get(0).(func(product.Product) error); ok {
		r0 = rf(Product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProduct provides a mock function with given fields: Product
func (_m *Repository) UpdateProduct(Product product.Product) error {
	ret := _m.Called(Product)

	var r0 error
	if rf, ok := ret.Get(0).(func(product.Product) error); ok {
		r0 = rf(Product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
