// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	purchasereceiving "AltaStore/business/purchasereceiving"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryDetail is an autogenerated mock type for the RepositoryDetail type
type RepositoryDetail struct {
	mock.Mock
}

// DeletePurchaseReceivingDetail provides a mock function with given fields: item
func (_m *RepositoryDetail) DeletePurchaseReceivingDetail(item *purchasereceiving.PurchaseReceivingDetail) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(*purchasereceiving.PurchaseReceivingDetail) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPurchaseReceivingDetailById provides a mock function with given fields: id
func (_m *RepositoryDetail) GetPurchaseReceivingDetailById(id string) (*purchasereceiving.PurchaseReceivingDetail, error) {
	ret := _m.Called(id)

	var r0 *purchasereceiving.PurchaseReceivingDetail
	if rf, ok := ret.Get(0).(func(string) *purchasereceiving.PurchaseReceivingDetail); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*purchasereceiving.PurchaseReceivingDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPurchaseReceivingDetailByPurchaseReceivingId provides a mock function with given fields: id
func (_m *RepositoryDetail) GetPurchaseReceivingDetailByPurchaseReceivingId(id string) (*[]purchasereceiving.PurchaseReceivingDetail, error) {
	ret := _m.Called(id)

	var r0 *[]purchasereceiving.PurchaseReceivingDetail
	if rf, ok := ret.Get(0).(func(string) *[]purchasereceiving.PurchaseReceivingDetail); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]purchasereceiving.PurchaseReceivingDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertPurchaseReceivingDetail provides a mock function with given fields: item
func (_m *RepositoryDetail) InsertPurchaseReceivingDetail(item *purchasereceiving.PurchaseReceivingDetail) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(*purchasereceiving.PurchaseReceivingDetail) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePurchaseReceivingDetail provides a mock function with given fields: item
func (_m *RepositoryDetail) UpdatePurchaseReceivingDetail(item *purchasereceiving.PurchaseReceivingDetail) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(*purchasereceiving.PurchaseReceivingDetail) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
